### PR TITLE
34 fixed cors error in chat

### LINKED ISSUE #34: Fixed cors error in chat

### PR DESCRIPTION
**Pull request by Jackdehaan**
Fixed the cors error by:
- Removing process.env.FRONTEND_URL from main.ts
- Changing the backend calls from the frontend in chat to https

### CODE REVIEW

File: frontend/src/Game/Matchmaking.tsx [hunk 1]
```diff
@@ -13,10 +13,10 @@ export default function MatchMaking() {
                 setMessage("Player ID can't be empty!");
                 return;
             }
-            const response = await axios.post('http://localhost:3000/queue/join', { playerId });
```
Comment (rubenfin) [inline frontend/src/Game/Matchmaking.tsx]: Can you change all the requests to use the generated api?

**Review by daanmlab — APPROVED** [review]
